---
title: "Cleaning and Recoding"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `vars_` series of functions are designed to simplify working with messy CCAO data. Current functions can rename columns to standard formats as well as recode numeric factors to their human-readable equivalents.

```{r setup, message=FALSE, results='asis'}
library(dplyr)
library(tidyr)
library(knitr)
library(ccao)

# Construct a fake data frame of commonly occuring CCAO column names and numeric
# encodings for factors
df <- tibble(
  PIN = rep("1234567", 4),
  GAR1_SIZE = c("1", "3", "0", NA),
  sale_price = rep(132324, 4),
  EXT_WALL = c("1", "2", "0", "4"),
  PORCH = c("1", NA, "3", "2")
)

df %>%
  kable(digits = 3)

# Recode variables 
df %>%
  vars_recode(type = "long") %>%
  kable(digits = 3)

# Rename variables to standard, then recode
df %>%
  vars_rename(names_to = "pretty") %>%
  vars_recode(type = "long") %>%
  kable(digits = 3)

```
