---
title: "Working with 288 data"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Below is an example showing the entire process of using the `chars_` functions to update characteristics data using an ADDCHARS extract. For more information on this process and why it is necessary, visit the [Home Improvement Exemptions](https://datascience.cookcountyassessor.com/wiki/residential/addchars.md) page on the internal DS wiki.

```{r, message=FALSE, results='asis'}
library(ccao)
library(dplyr)
library(tidyr)
library(knitr)

# Choose a random sample PIN from the sample ADDCHARS data
sample_chars <- chars_sample_addchars %>%
  filter(QU_PIN == "05273000030000")

# This PIN has a basement and garage renovation followed by a bathroom reno
# three years later
sample_chars %>%
  select(
    QU_PIN, TAX_YEAR, QU_CLASS,
    QU_TOWN, QU_GARAGE_SIZE, QU_SQFT_BLD, QU_BEDS
  ) %>%
  kable(format = "markdown", digits = 3)

# Sparsify the data. You can see that one 288 ends roughly when the other one
# begins. NOTE: the mutate() on QU_CLASS here is because sometime QU_CLASS is
# equal to 0 (mostly for garage renovations). This is an easy fix
sparse_chars <- sample_chars %>%
  arrange(QU_PIN, TAX_YEAR, QU_CLASS) %>%
  mutate(QU_CLASS = ifelse(QU_CLASS == 0, lag(QU_CLASS), QU_CLASS)) %>%
  chars_sparsify(
    pin_col = QU_PIN,
    year_col = TAX_YEAR, 
    class_col = QU_CLASS,
    town_col = as.character(QU_TOWN),
    upload_date_col = QU_UPLOAD_DATE,
    additive_source = any_of(chars_cols$add_source),
    replacement_source = any_of(chars_cols$rep_source)
  ) %>%
  mutate(QU_CLASS = substr(QU_CLASS, 1, 3))

# The resulting sparse data can be joined onto any data containing CCAOSFCHARS
sparse_chars %>%
  select(
    QU_PIN, YEAR, QU_CLASS, QU_GARAGE_SIZE, 
    QU_SQFT_BLD, QU_BEDS, NUM_288S_ACTIVE
  ) %>%
  kable(format = "markdown", digits = 3)

# Here is an example data frame where the sparse data is merged onto
# characteristic data and the characteristics are then updated using chars_update()
updated_chars <- chars_sample_universe %>%
  filter(PIN %in% sample_chars$QU_PIN) %>%
  left_join(
    sparse_chars,
    by = c("PIN" = "QU_PIN", "TAX_YEAR" = "YEAR", "CLASS" = "QU_CLASS")
  ) %>%
  arrange(PIN, TAX_YEAR) %>%
  chars_update(
    additive_target = any_of(ccao::chars_cols$add_target),
    replacement_target = any_of(ccao::chars_cols$rep_target)
  )

# Show updated characteristics vs ADDCHARS
updated_chars %>%
  ungroup() %>%
  select(
    PIN, TAX_YEAR, CLASS, NUM_288S_ACTIVE, GAR1_SIZE, QU_GARAGE_SIZE,
    BLDG_SF, QU_SQFT_BLD, BEDS, QU_BEDS
  ) %>%
  arrange(PIN, CLASS, TAX_YEAR) %>%
  kable(format = "markdown", digits = 3)

```
