on:
  pull_request:
  push:
    branches: [main, master]

name: pytest-coverage

env:
  PYTHONUNBUFFERED: "1"
  UV_SYSTEM_PYTHON: 1

jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
            # Test the lower bound of pandas/numpy support for Python 3.9,
            # and test the upper bound for all other Python versions
          - python: "3.9"
            pandas: "1.4.*"
            numpy: "1.23.*"
          - python: "3.10"
            pandas: "2.2.*"
            numpy: "2.1.*"
          - python: "3.11"
            pandas: "2.2.*"
            numpy: "2.1.*"
          - python: "3.12"
            pandas: "2.2.*"
            numpy: "2.1.*"
          - python: "3.13"
            pandas: "2.2.*"
            numpy: "2.1.*"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: python/pyproject.toml
        cache-suffix: test

    - name: Install Python ${{ matrix.version.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version.python }}

    - name: Install pandas ${{ matrix.version.pandas }} and numpy ${{ matrix.version.numpy }}
      working-directory: python
      shell: bash
      run: |
        uv pip install \
          pandas==${{ matrix.version.pandas }} \
          numpy==${{ matrix.version.numpy}}

    - name: Install Python dependencies
      working-directory: python
      shell: bash
      run: uv pip install .[dev,docs]

    - name: Run pytest
      working-directory: python
      shell: bash
      run: |
        pytest -v --doctest-modules \
          --junitxml=junit/test-results-${{ matrix.version.python }}.xmlpytest

    - name: Upload artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: python/pytest-results-${{ matrix.version.python }}
        path: python/junit/test-results-${{ matrix.version.python }}.xml
